<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;

/**
 * Ps Controller
 *
 * @property \App\Model\Table\PsTable $Ps
 *
 * @method \App\Model\Entity\Ps[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class PsController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->viewBuilder()->setLayout('mainframe');// TODO: Change the autogenerated stub
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $ps = $this->paginate($this->Ps);

        $this->set(compact('ps'));
    }

    /**
     * View method
     *
     * @param string|null $id P id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $ps = $this->Ps->get($id, [
            'contain' => []
        ]);

        $this->set('ps', $ps);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $ps = $this->Ps->newEntity();
        if ($this->request->is('post')) {
            $ps = $this->Ps->patchEntity($ps, $this->request->getData());
            if ($this->Ps->save($ps)) {
                $this->Flash->success(__('The p has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The p could not be saved. Please, try again.'));
        }
        $this->set(compact('ps'));
    }

    /**
     * Edit method
     *
     * @param string|null $id P id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $ps = $this->Ps->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $ps = $this->Ps->patchEntity($ps, $this->request->getData());
            if ($this->Ps->save($ps)) {
                $this->Flash->success(__('The p has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The p could not be saved. Please, try again.'));
        }
        $this->set(compact('ps'));
    }

    /**
     * Delete method
     *
     * @param string|null $id P id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $ps = $this->Ps->get($id);
        if ($this->Ps->delete($ps)) {
            $this->Flash->success(__('The p has been deleted.'));
        } else {
            $this->Flash->error(__('The p could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
    public function scheduler(){

    }
    public function dailyReport(){
//        $this->autoRender = false;
//        echo "<pre>";
//        print_r($this->request);
//        echo "</pre>";
        $date = $this->request->getQuery('date');
        $urlToSales = 'http://salesmodule.acumenits.com/api/all-data';

        $optionsForSales = [
            'http' => [
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'GET'
            ]
        ];
        $contextForSales  = stream_context_create($optionsForSales);
        $resultFromSales = file_get_contents($urlToSales, false, $contextForSales);
        if ($resultFromSales === FALSE) {
            echo 'ERROR!!';
        }
        $ps = $this->Ps->newEntity();
        if ($this->request->is(['post'])) {
            $ps->date = date('d-m-Y');
            $ps->created_by = 'requester';
            $ps->status = 'requested';
            if ($this->Ps->save($ps)) {
                $ps_no = $this->Ps->find('all', ['fields' => 'id'])->last();
                if($this->request->getData('count') != null){
                    $dr = TableRegistry::get('dr');
                    $drData = array();
                    for($i = 0; $i <= $this->request->getData('count'); $i++){
                        $drData[$i]['ps_id'] = $ps_no['id'];
                        $drData[$i]['so_no'] = $this->request->getData('so_no'.$i);
                        $drData[$i]['item_no'] = $this->request->getData('item_no'.$i);
                        $drData[$i]['quantity'] = $this->request->getData('quantity'.$i);
                    }
                    $pss = $dr->newEntities($drData);
                    foreach($pss as $ps){
                        $dr->save($ps);
                    }
                }
                $this->Flash->success(__('The scn has been saved.'));

                return $this->redirect(['action' => 'daily-report?date='.date('d-m-Y')]);
            }
            $this->Flash->error(__('The ps could not be saved. Please, try again.'));
        }
        $dataFromSales = json_decode($resultFromSales);
        $this->set('sales',$dataFromSales);
        $this->set('date',$date);
    }
}
