<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Model\Entity\WipSection;
use Cake\ORM\TableRegistry;

/**
 * Wip Controller
 *
 * @property \App\Model\Table\WipTable $Wip
 *
 * @method \App\Model\Entity\Wip[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class WipController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->viewBuilder()->setLayout('mainframe');// TODO: Change the autogenerated stub
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $wip = $this->paginate($this->Wip);
        $this->loadModel('Wip');
        $this->loadModel('SerialNumber');
        $this->loadModel('WipSection');
        $wip = $this->Wip->find('all');
        foreach ($wip as $wp){
            $sn_details = $this->SerialNumber->find('all')
                ->Where(['id'=>$wp->serial_no]);
            foreach ($sn_details as $snd){
                $wp->sn_details = $snd;
            }
            $wip_sec = $this->WipSection->find('all')
                ->Where(['wip_id'=>$wp->id]);
            foreach ($wip_sec as $wips){
                if($wips->status === 'requested'){
                    $wp->status = 'Pending';
                }
            }
        }
        $this->set('wip', $wip);
    }

    /**
     * View method
     *
     * @param string|null $id Wip id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $this->loadModel('SerialNumber');
        $this->loadModel('WipSection');
        $wip = $this->Wip->find('all')
            ->where(['id'=> $id]);
        foreach ($wip as $w) {
            $sn_details = $this->SerialNumber->find('all')
                ->Where(['id' => $w->serial_no]);
            foreach ($sn_details as $snd) {
                $w->sn_details = $snd;
            }
            $wip_sec = $this->WipSection->find('all')
                ->Where(['wip_id'=>$id]);
                $w->wip_sec = $wip_sec;
        }
        $this->set('pic', $this->Auth->user('username'));
        $this->set('wip', $wip);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $this->loadModel('SerialNumber');
        $this->loadModel('WipSection');
        $sn = $this->SerialNumber->find('all');
        $sn_id =null;
        foreach($sn as $s){
            $sn_id .= '{label:"'.$s->so_no.'",idx:"'.$s->id.'",idy:"'.$s->model.'",idz:"'.$s->version.'"},';
        }
        $wip = $this->Wip->newEntity();
        if ($this->request->is('post')) {
            $this->autoRender = false;
            $wip = $this->Wip->patchEntity($wip, $this->request->getData());
//            if($this->request->getData('cb_1') == '' || $this->request->getData('cb_2') == '' || $this->request->getData('cb_3') == '' || $this->request->getData('cb_4') == '' || $this->request->getData('cb_5') == '' || $this->request->getData('cb_6') == '' || $this->request->getData('cb_7') == '' || $this->request->getData('cb_8') == '' || $this->request->getData('cb_9') == '') {
//                $this->Flash->error(__('The wp could not be saved. Please, try again.'));
//                return $this->redirect(['action' => 'add']);
//            }
            if ($this->Wip->save($wip)) {
                $wip_no = $this->Wip->find('all', ['fields' => 'id'])->last();
                for($i =1;$i<=9;$i++){
                    if($this->request->getData('cb_'.$i) != ''){
                        $wips = $this->WipSection->newEntity();
                        $wips->wip_id = $wip_no['id'];
                        $wips->operator_name =$this->request->getData('operator_name_'.$i);
                        $wips->supervisor_name =  $this->request->getData('supervisor_name_'.$i);
                        $wips->section = $this->request->getData('section'.$i);
                        $wips->status = 'requested';
                        $this->WipSection->save($wips);
                    }
                }
                $this->Flash->success(__('The wp has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The wp could not be saved. Please, try again.'));
        }
        $count = $this->Wip->find('all')->last();
        $this->set(compact('wip'));
        $this->set('sn_id',$sn_id);
        $this->set('wp_no', (isset($count->id) ? ($count->id + 1) : 1));
        $this->set('pic', $this->Auth->user('username'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Wip id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $this->loadModel('WipSection');
        $wip = $this->WipSection->get($id, [
            'contain' => []
        ]);

        if ($this->request->is(['patch', 'post', 'put'])) {
            $wip = $this->WipSection->patchEntity($wip, $this->request->getData());
            if ($this->WipSection->save($wip)) {
                $this->Flash->success(__('The wip has been saved.'));

                return $this->redirect(['action' => 'view',$wip->wip_id]);
            }
            $this->Flash->error(__('The wip could not be saved. Please, try again.'));
        }
        $this->set(compact('wip'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Wip id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $wip = $this->Wip->get($id);
        if ($this->Wip->delete($wip)) {
            $this->Flash->success(__('The wip has been deleted.'));
        } else {
            $this->Flash->error(__('The wip could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
    public function report(){
        $wip = $this->paginate($this->Wip);
        $this->loadModel('SerialNumber');
        $this->loadModel('WipSection');
        $wip = $this->Wip->find('all');
        foreach ($wip as $wp){
            $sn_details = $this->SerialNumber->find('all')
                ->Where(['id'=>$wp->serial_no]);
            foreach ($sn_details as $snd){
                $wp->sn_details = $snd;
            }
            $wip_sec = $this->WipSection->find('all')
                ->Where(['wip_id'=>$wp->id]);
            $wp->wip_sec= $wip_sec;
        }
        $this->set('wip', $wip);
    }
}
